### PR TITLE
Add staticpod

### PR DESCRIPTION
**Pull request by luomengY**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Accidentally deleted the fork of kubedge/kubernetes, #10 cannot be reopened.
#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubeedge/kubernetes/pull/10

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by luomengY** [comment]
Can this PR be merged into the kubeedge:v1.24.14-kubeedge branch? After I accidentally deleted the fork of kubeedge/kubernetes a few days ago, I found that the PR was also closed and could not be reopened. In order to avoid it happening again. , it is recommended that it may be better to merge into the corresponding branch. @Shelley-BaoYue

**Comment by Shelley-BaoYue** [comment]
The PR has been merged into the branch corresponding to 1.26 as a feature, it will not be merged into the branch corresponding to 1.24.

**Comment by luomengY** [comment]
> The PR has been merged into the branch corresponding to 1.26 as a feature, it will not be merged into the branch corresponding to 1.24.

ok

**Pull request closed without merging**
