### PR TITLE
add static pod【wip】

### PR DESCRIPTION
**Pull request by luomengY**
#### What this PR does / why we need it:
Add support for static pod functionality in edge.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubeedge/kubeedge/issues/4778

@Shelley-BaoYue

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
`DCO` failed, please using `git commit -s`.

**Comment by Shelley-BaoYue** [comment]
How about revert this history commit 'https://github.com/kubeedge/kubernetes/commit/a4309c3d0530e205ff7e3537ce28a902b19fb9cb#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530'?

**Comment by luomengY** [comment]
> How about revert this history commit '[a4309c3#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530](https://github.com/kubeedge/kubernetes/commit/a4309c3d0530e205ff7e3537ce28a902b19fb9cb#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530)'?

This seems to be only about mirror pod, and the content of static pod has some modifications based on the original K8S.

**Comment by Shelley-BaoYue** [comment]
> > How about revert this history commit '[a4309c3#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530](https://github.com/kubeedge/kubernetes/commit/a4309c3d0530e205ff7e3537ce28a902b19fb9cb#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530)'?
> 
> This seems to be only about mirror pod, and the content of static pod has some modifications based on the original K8S.

This commit also contains some modification about static pod. I compare these two commits and the content is not much different. 

I think we can see if we can revert the this commit? If we have some necessart intrusive changes, we can create a separate commit.  This way, we can track Kubernetes updates in real time.

**Comment by luomengY** [comment]
> > > How about revert this history commit '[a4309c3#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530](https://github.com/kubeedge/kubernetes/commit/a4309c3d0530e205ff7e3537ce28a902b19fb9cb#diff-f2e4d3632822fde7e6617f2729849074b6f9287c3ad86479f351f293558cb530)'?
> > 
> > 
> > This seems to be only about mirror pod, and the content of static pod has some modifications based on the original K8S.
> 
> This commit also contains some modification about static pod. I compare these two commits and the content is not much different.
> 
> I think we can see if we can revert the this commit? If we have some necessart intrusive changes, we can create a separate commit. This way, we can track Kubernetes updates in real time.

Okay, let's restore it. Let me compare the changes I made and I'll bring up another PR.

**Comment by Shelley-BaoYue** [comment]
Is this PR still working in progress?  If so, you can add `WIP` in your title. And remove it when you complete this work.

I wish this pr split into two commits, one named `Revert xxxx` which is automatically generated by using `git revert`, another is used to add your modification for static pod.  So that we can clearly trace all modification for kubernetes in history commits.

**Comment by luomengY** [comment]
> Is this PR still working in progress? If so, you can add `WIP` in your title. And remove it when you complete this work.
> 
> I wish this pr split into two commits, one named `Revert xxxx` which is automatically generated by using `git revert`, another is used to add your modification for static pod. So that we can clearly trace all modification for kubernetes in history commits.

ok!

**Comment by Shelley-BaoYue** [comment]
/close 
a new PR in #10

**Pull request closed without merging**
